[2025-06-20 17:47:44 +0000] [745491] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['127.0.0.1:8001']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 300
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: True
  reload_engine: auto
  reload_extra_files: ['/home/team_samarastudios_com/yueBpw/vertex/server.py']
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/team_samarastudios_com/yueBpw/YuE-exllamav2/src
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 2142963865
  group: 2142963865
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/team_samarastudios_com/yueBpw/vertex/logs/gunicorn/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/team_samarastudios_com/yueBpw/vertex/logs/gunicorn/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: ../../vertex/server:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fb696710700>
  on_reload: <function OnReload.on_reload at 0x7fb696710820>
  when_ready: <function WhenReady.when_ready at 0x7fb696710940>
  pre_fork: <function Prefork.pre_fork at 0x7fb696710a60>
  post_fork: <function Postfork.post_fork at 0x7fb696710b80>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fb696710ca0>
  worker_int: <function WorkerInt.worker_int at 0x7fb696710dc0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fb696710ee0>
  pre_exec: <function PreExec.pre_exec at 0x7fb696711000>
  pre_request: <function PreRequest.pre_request at 0x7fb696711120>
  post_request: <function PostRequest.post_request at 0x7fb6967111b0>
  child_exit: <function ChildExit.child_exit at 0x7fb6967112d0>
  worker_exit: <function WorkerExit.worker_exit at 0x7fb6967113f0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fb696711510>
  on_exit: <function OnExit.on_exit at 0x7fb696711630>
  ssl_context: <function NewSSLContext.ssl_context at 0x7fb696711750>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2025-06-20 17:47:44 +0000] [745491] [INFO] Starting gunicorn 23.0.0
[2025-06-20 17:47:44 +0000] [745491] [ERROR] Connection in use: ('127.0.0.1', 8001)
[2025-06-20 17:47:44 +0000] [745491] [ERROR] connection to ('127.0.0.1', 8001) failed: [Errno 98] Address already in use
[2025-06-20 17:47:44 +0000] [745491] [DEBUG] Retrying in 1 second.
[2025-06-20 17:47:45 +0000] [745491] [ERROR] Connection in use: ('127.0.0.1', 8001)
[2025-06-20 17:47:45 +0000] [745491] [ERROR] connection to ('127.0.0.1', 8001) failed: [Errno 98] Address already in use
[2025-06-20 17:47:45 +0000] [745491] [DEBUG] Retrying in 1 second.
[2025-06-20 17:47:46 +0000] [745491] [ERROR] Connection in use: ('127.0.0.1', 8001)
[2025-06-20 17:47:46 +0000] [745491] [ERROR] connection to ('127.0.0.1', 8001) failed: [Errno 98] Address already in use
[2025-06-20 17:47:46 +0000] [745491] [DEBUG] Retrying in 1 second.
[2025-06-20 17:47:47 +0000] [745491] [ERROR] Connection in use: ('127.0.0.1', 8001)
[2025-06-20 17:47:47 +0000] [745491] [ERROR] connection to ('127.0.0.1', 8001) failed: [Errno 98] Address already in use
[2025-06-20 17:47:47 +0000] [745491] [DEBUG] Retrying in 1 second.
[2025-06-20 17:47:48 +0000] [745491] [ERROR] Connection in use: ('127.0.0.1', 8001)
[2025-06-20 17:47:48 +0000] [745491] [ERROR] connection to ('127.0.0.1', 8001) failed: [Errno 98] Address already in use
[2025-06-20 17:47:48 +0000] [745491] [DEBUG] Retrying in 1 second.
[2025-06-20 17:47:49 +0000] [745491] [ERROR] Can't connect to ('127.0.0.1', 8001)
